services:
  vividtex:
    build: .
    container_name: vividtex
    ports:
      - "3001:3001" # Backend API
      - "1234:1234" # WebSocket
    env_file:
      - .env
    environment:
      - VIVIDTEX_WORKDIR=/app/workspace
    volumes:
      - /home/laim/workspace:/app/workspace
    working_dir: /app
